### ISSUE TITLE
1.12.2 crash

### ISSUE THREAD

**Issue by Los2tale** [kyeiti/UndergroundBiomesConstructs#12]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.2-universal.jar)
  ISCore (ImprovableSkills_1.12.2-3.4.1r.jar)
  ItemPatchingLoader (ItemPhysic_Full+1.4.11_mc1.12.2.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.9.5.9.jar)
  VanillaFixLoadingPlugin (VanillaFix-1.0.5-43.jar)
  llibrary (llibrary-1.7.9-1.12.2.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  ImprovedMobs/ASM (ImprovedMobs-1.2.0[1.12.2].jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 5/23/18 1:41 AM
Description: Initializing game

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at thelm.jaopca.api.EnumEntryType.lambda$getRegisterer$12(EnumEntryType.java:115)
	at thelm.jaopca.registry.RegistryCore.registerEntries(RegistryCore.java:243)
	at thelm.jaopca.registry.RegistryCore.preInit1(RegistryCore.java:76)
	at thelm.jaopca.utils.JAOPCAEventHandler.onRegistryWrapUp(JAOPCAEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_737_JAOPCAEventHandler_onRegistryWrapUp_Event2.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at thelm.wrapup.WrapUp.onVillagerProfessionRegisterLowest(WrapUp.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_363_WrapUp_onVillagerProfessionRegisterLowest_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:750)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
	at net.minecraft.client.Minecraft.init(Minecraft.java:466)
	at net.minecraft.client.Minecraft.run(Minecraft.java:3889)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at thelm.jaopca.api.EnumEntryType.lambda$getRegisterer$12(EnumEntryType.java:112)
	at thelm.jaopca.registry.RegistryCore.registerEntries(RegistryCore.java:243)
	at thelm.jaopca.registry.RegistryCore.preInit1(RegistryCore.java:76)
	at thelm.jaopca.utils.JAOPCAEventHandler.onRegistryWrapUp(JAOPCAEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_737_JAOPCAEventHandler_onRegistryWrapUp_Event2.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at thelm.wrapup.WrapUp.onVillagerProfessionRegisterLowest(WrapUp.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_363_WrapUp_onVillagerProfessionRegisterLowest_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:750)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3889)
	... 7 more
Caused by: java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:293)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:279)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:112)
	at thelm.jaopca.registry.RegistryCore.registerBlocks(RegistryCore.java:272)
	... 29 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thelm.jaopca.api.EnumEntryType.lambda$getRegisterer$12(EnumEntryType.java:115)
	at thelm.jaopca.registry.RegistryCore.registerEntries(RegistryCore.java:243)
	at thelm.jaopca.registry.RegistryCore.preInit1(RegistryCore.java:76)
	at thelm.jaopca.utils.JAOPCAEventHandler.onRegistryWrapUp(JAOPCAEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_737_JAOPCAEventHandler_onRegistryWrapUp_Event2.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at thelm.wrapup.WrapUp.onVillagerProfessionRegisterLowest(WrapUp.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_363_WrapUp_onVillagerProfessionRegisterLowest_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:750)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
	at net.minecraft.client.Minecraft.init(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:3889)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 280573856 bytes (267 MB) / 832528384 bytes (793 MB) up to 8576565248 bytes (8179 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2702 106 mods loaded, 106 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                 | Source                                                | Signature                                |
	|:----- |:-------------------- |:----------------------- |:----------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2                  | minecraft.jar                                         | None                                     |
	| UCH   | mcp                  | 9.42                    | minecraft.jar                                         | None                                     |
	| UCH   | FML                  | 8.0.99.99               | forge-1.12.2-14.23.3.2702.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.3.2702            | forge-1.12.2-14.23.3.2702.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | creativecoredummy    | 1.0.0                   | minecraft.jar                                         | None                                     |
	| UCH   | itemphysic           | 1.4.0                   | minecraft.jar                                         | None                                     |
	| UCH   | ivtoolkit            | 1.3.3-1.12              | minecraft.jar                                         | None                                     |
	| UCH   | foamfixcore          | 7.7.4                   | minecraft.jar                                         | None                                     |
	| UCH   | advancedsticks       | 1.5.7                   | Advanced+Sticks+1.12++by+XxRexRaptorxX+(v.1.5.7).jar  | None                                     |
	| UCH   | orbis_api            | 1.12.2-1.1              | orbis_api-1.12.2-1.1.jar                              | None                                     |
	| UCH   | aether               | 1.12.2-1.0.4            | aether_ii-1.12.2-1.0.4.jar                            | None                                     |
	| UCH   | ageofweapons         | 0.13.5                  | Age+of+Weapons+1.12.2++(v.0.13.5).jar                 | None                                     |
	| UCH   | aiimprovements       | 0.0.1.1                 | AIImprovements-1.12.1-0.0.1b1.jar                     | None                                     |
	| UCH   | biomesoplenty        | 7.0.1.2390              | BiomesOPlenty-1.12.2-7.0.1.2390-universal.jar         | None                                     |
	| UCH   | craftstudioapi       | 1.0.0                   | CraftStudio-1.0.0.93-mc1.12-alpha.jar                 | None                                     |
	| UCH   | animania             | 1.4.7                   | animania-1.12.2-1.4.8.jar                             | None                                     |
	| UCH   | applecore            | 3.1.1                   | AppleCore-mc1.12.2-3.1.1.jar                          | None                                     |
	| UCH   | aquaculture          | 1.6.2                   | Aquaculture-1.12.2-1.6.2.jar                          | None                                     |
	| UCH   | thedragonlib         | 1.12.2-5.2.0            | thedragonlib-1.12.2-5.2.0.jar                         | None                                     |
	| UCH   | armorplus            | 1.12.2-11.13.0.40       | armorplus-1.12.2-11.13.0.40.jar                       | None                                     |
	| UCH   | as_extraresources    | 1.0.8                   | AS-ExtraResources+1.12+by+XxRexRaptorxX+(v.1.0.8).jar | None                                     |
	| UCH   | basemetals           | 2.5.0-beta5             | BaseMetals-1.12-2.5.0-beta5.214.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | baseminerals         | 2.5.0-beta5             | BaseMinerals-1.12-2.5.0-beta5.43.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | betterunderground    | 1.1.6                   | betterunderground-1.1.6.jar                           | None                                     |
	| UCH   | bibliocraft          | 2.4.3                   | BiblioCraft[v2.4.3][MC1.12.0].jar                     | None                                     |
	| UCH   | jei                  | 4.9.1.189               | jei_1.12.2-4.9.1.189.jar                              | None                                     |
	| UCH   | forestry             | 5.8.0.291               | forestry_1.12.2-5.8.0.291.jar                         | None                                     |
	| UCH   | binniecore           | 2.5.0.164               | binnie-mods-1.12.2-2.5.0.164.jar                      | None                                     |
	| UCH   | binniedesign         | 2.5.0.164               | binnie-mods-1.12.2-2.5.0.164.jar                      | None                                     |
	| UCH   | genetics             | 2.5.0.164               | binnie-mods-1.12.2-2.5.0.164.jar                      | None                                     |
	| UCH   | botany               | 2.5.0.164               | binnie-mods-1.12.2-2.5.0.164.jar                      | None                                     |
	| UCH   | extrabees            | 2.5.0.164               | binnie-mods-1.12.2-2.5.0.164.jar                      | None                                     |
	| UCH   | extratrees           | 2.5.0.164               | binnie-mods-1.12.2-2.5.0.164.jar                      | None                                     |
	| UCH   | candymod             | 0.4.3                   | candyworld-0.4.3.jar                                  | None                                     |
	| UCH   | carryon              | 1.9                     | CarryOn+MC1.12.2+v1.9.jar                             | None                                     |
	| UCH   | cavern               | 2.1.6                   | Cavern_1.12.2-v2.1.6.jar                              | None                                     |
	| UCH   | chameleon            | 1.12-4.1.3              | Chameleon-1.12-4.1.3.jar                              | None                                     |
	| UCH   | storagedrawers       | 1.12-5.3.5              | StorageDrawers-1.12.2-5.3.6.jar                       | None                                     |
	| UCH   | compactdrawers       | 1.12.2-1.0.1.67         | CompactDrawers-1.12.2-1.0.1.67.jar                    | None                                     |
	| UCH   | compactstorage       | 3.0                     | CompactStorage-3.0-10.jar                             | None                                     |
	| UCH   | containerfix         | 1.0                     | ContainerFix+MC1.12.2+v1.0.jar                        | None                                     |
	| UCH   | cookingforblockheads | 6.3.26                  | CookingForBlockheads_1.12.2-6.3.26.jar                | None                                     |
	| UCH   | extendedrenderer     | v1.0                    | coroutil-1.12.1-1.2.11.jar                            | None                                     |
	| UCH   | coroutil             | 1.12.1-1.2.11           | coroutil-1.12.1-1.2.11.jar                            | None                                     |
	| UCH   | configmod            | v1.0                    | coroutil-1.12.1-1.2.11.jar                            | None                                     |
	| UCH   | creativecore         | 1.9.9                   | CreativeCore_v1.9.22_mc1.12.2.jar                     | None                                     |
	| UCH   | customspawner        | 3.11.4                  | CustomMobSpawner-3.11.4.jar                           | None                                     |
	| UCH   | customstuff4         | 0.5.2                   | customstuff4-1.12.2-0.5.2.jar                         | None                                     |
	| UCH   | orespawn             | 3.3.0                   | OreSpawn-1.12-3.3.0.136.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | densemetals          | 1.2.0                   | DenseMetals-1.12-1.2.0.20.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | mocreatures          | 12.0.4                  | DrZharks MoCreatures Mod-12.0.4.jar                   | None                                     |
	| UCH   | gottschcore          | 1.3.5                   | GottschCore-mc1.12.2-f14.23.2.2611-v1.3.5.jar         | None                                     |
	| UCH   | dungeons2            | 1.3.3                   | Dungeons2-mc1.12.2-f14.23.1.2555-v1.3.3.jar           | None                                     |
	| UCH   | dungeontactics       | DT-0.14.2               | DungeonTactics-1.12.2-0.14.2.jar                      | None                                     |
	| UCH   | equipmenttooltips    | 1.0.3                   | EquipmentTooltips-1.12.2-1.0.3-4.jar                  | None                                     |
	| UCH   | erebus               | 1.0.22                  | Erebus-1.0.22.jar                                     | None                                     |
	| UCH   | exoticbirds          | 1.0                     | Exotic+Birds+1.12.2-1.4.1.jar                         | None                                     |
	| UCH   | fairylights          | 2.1.2                   | fairylights-2.1.2-1.12.x.jar                          | None                                     |
	| UCH   | farmingforblockheads | 3.1.17                  | FarmingForBlockheads_1.12.2-3.1.17.jar                | None                                     |
	| UCH   | foamfix              | 0.9.9.1-1.12.2          | foamfix-0.9.9.1-1.12.2-anarchy.jar                    | None                                     |
	| UCH   | hammercore           | 1.9.9.5.9               | HammerCore-1.12.2-1.9.9.5.9.jar                       | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCH   | llibrary             | 1.7.9                   | llibrary-1.7.9-1.12.2.jar                             | None                                     |
	| UCH   | iceandfire           | 1.4.0                   | iceandfire-1.4.0-1.12.2.jar                           | None                                     |
	| UCH   | improvableskills     | 3.4.1r                  | ImprovableSkills_1.12.2-3.4.1r.jar                    | None                                     |
	| UCH   | improvedmobs         | 1.2.0[1.12.2]           | ImprovedMobs-1.2.0[1.12.2].jar                        | None                                     |
	| UCH   | ironbackpacks        | 1.12.2-3.0.7-10         | IronBackpacks-1.12.2-3.0.7-10.jar                     | None                                     |
	| UCH   | jaopca               | 1.12.2-2.2.6.83         | JAOPCA-1.12.2-2.2.6.83.jar                            | None                                     |
	| UCH   | oredictinit          | 1.12.2-2.2.1.67         | JAOPCA-1.12.2-2.2.6.83.jar                            | None                                     |
	| UCH   | jaopcaadditions      | 1.12.2-2.2.1.9          | JAOPCAAdditions-1.12.2-2.2.1.9.jar                    | None                                     |
	| UCH   | harvestcraft         | 1.12.2u                 | Pam's+HarvestCraft+1.12.2u.jar                        | None                                     |
	| UCH   | jehc                 | 1.12.2                  | JEHC-1.12.2-1.5.1.0.jar                               | None                                     |
	| UCH   | jeibees              | 0.9.0.5                 | jeibees-0.9.0.5-mc1.12.2.jar                          | None                                     |
	| UCH   | jjmeteor             | 1.0.6                   | JJ+Meteor+1.12-1.12.2-v1.0.6.jar                      | None                                     |
	| UCH   | jjskill              | 1.0.0                   | JJ+Skill+1.12-1.12.2-v1.0.0.jar                       | None                                     |
	| UCH   | jeresources          | 0.8.7.41                | JustEnoughResources-1.12.2-0.8.7.41.jar               | None                                     |
	| UCH   | lucky                | 7.5.0                   | LuckyBlock_1-12_v7-5-0.zip                            | None                                     |
	| UCH   | macrokey             | 1.12.x-2.0.0-BETA.b90   | MacroKey+Keybinding-1.12.x-2.0.0-BETA.b90.jar         | None                                     |
	| UCH   | metalchests          | v1.2.2.g3d3d54b         | MetalChests-v1.2.2.g3d3d54b.jar                       | None                                     |
	| UCH   | modernmetals         | 2.5.0-beta5             | ModernMetals-1.12-2.5.0-beta5.120.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | morebeautifulbuttons | 1.12.2-1.7.3.20         | morebeautifulbuttons-1.12.2-1.7.3.20.jar              | None                                     |
	| UCH   | multiplelights       | 1.0.1                   | MultipleLights-1.12.x-1.0.1.jar                       | None                                     |
	| UCH   | mysticalwildlife     | 1.1.1                   | mysticalwildlife-1.12.2-1.1.1.jar                     | None                                     |
	| UCH   | nex                  | 2.1.14.15               | NetherEx-1.12-2.1.14.15.jar                           | None                                     |
	| UCH   | oresalleasy          | 0.1.0.18                | OresAllEasy-1.12.2-0.1.0.18.jar                       | None                                     |
	| UCH   | primitivemobs        | 1.1.6                   | primitivemobs-1.1.6_beta.jar                          | None                                     |
	| UCH   | reccomplex           | 1.4.7                   | RecurrentComplex-1.4.7.jar                            | None                                     |
	| UCH   | roguelike            | 1.8.0                   | RoguelikeDungeons-1.12.2-1.8.0.jar                    | None                                     |
	| UCH   | ruins                | 17.1                    | Ruins-1.12.2.jar                                      | None                                     |
	| UCH   | sereneseasons        | 1.2.2                   | SereneSeasons-1.12.2-1.2.2-universal.jar              | None                                     |
	| UCH   | shipwrecks_winslow   | 2.0.0                   | shipwrecks-mc1.12.2-2.0.0.jar                         | None                                     |
	| UCH   | spartanshields       | 1.4.1                   | SpartanShields-1.12.2-1.4.1.jar                       | None                                     |
	| UCH   | storagedrawersextra  | @VERSION@               | StorageDrawersExtras-1.12-3.1.0.jar                   | None                                     |
	| UCH   | thebetweenlands      | 3.3.8                   | TheBetweenlands-3.3.8-universal.jar                   | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCH   | treasure2            | 0.5.3                   | Treasure2-mc1.12.2-f14.23.1.2555-alpha0.5.3.jar       | None                                     |
	| UCH   | twilightforest       | 3.7.424                 | twilightforest-1.12.2-3.7.424-universal.jar           | None                                     |
	| UCH   | undergroundbiomes    | 1.1.2                   | UndergroundBiomesConstructs-1.12-1.1.2.jar            | None                                     |
	| UCH   | of                   | 0.3                     | Useful+Interior+-+0.3+[1.12.2].jar                    | None                                     |
	| UCH   | vanillafix           | 1.0.5+43                | VanillaFix-1.0.5-43.jar                               | None                                     |
	| UCH   | vanillafoodpantry    | 4.1.0                   | vanillafoodpantry-mc1.12.1-4.1.0.jar                  | None                                     |
	| UCH   | venomousfangs        | 1.1                     | VenomousFangs1.12-1.1.jar                             | None                                     |
	| UCH   | zlbuilding           | 1.1.0                   | ZL-BuildingAdditions_1.12.2-r4.jar                    | None                                     |
	| UCH   | zombie_players       | 1.12.1-1.1.1            | zombie_players-1.12.1-1.1.1.jar                       | None                                     |
	| UCH   | zombieawareness      | 1.12.1-1.11.12          | zombieawareness-1.12.1-1.11.12.jar                    | None                                     |
	| UCH   | lightorbs            | 0.3.0                   | lightorbs-Alpha+0.3.0.jar                             | None                                     |
	| UCH   | hungeroverhaul       | 1.12.2-1.3.2.jenkins146 | HungerOverhaul-1.12.2-1.3.2.jenkins146.jar            | None                                     |
	| UCH   | wrapup               | 1.12-1.1.3              | WrapUp-1.12-1.1.3.jar                                 | None                                     |

	Loaded coremods (and transformers): 
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.2-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ISCore (ImprovableSkills_1.12.2-3.4.1r.jar)
  com.endie.is.asm.ImprovableSkillsTransformer
ItemPatchingLoader (ItemPhysic_Full+1.4.11_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
HammerCoreCore (HammerCore-1.12.2-1.9.9.5.9.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
VanillaFixLoadingPlugin (VanillaFix-1.0.5-43.jar)
  
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ImprovedMobs/ASM (ImprovedMobs-1.2.0[1.12.2].jar)
  com.flemmli97.improvedmobs.asm.ASMTransformer
AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
  
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4749' Renderer: 'Intel(R) HD Graphics 530'
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 3065 names; 5690 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KYmxvY2tzIHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSBhZGQgQ2h1bmsgTG9hZGVyIGJsb2NrPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOkNodW5rTG9hZGVyPXRydWUNCg0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGFkZCBUZXNzZXJhY3QgYmxvY2s/IFtkZWZhdWx0OiBmYWxzZV0NCiAgICBCOlRlc3NlcmFjdD1mYWxzZQ0KfQ0KDQoNCmNsaWVudCB7DQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcmVwbGFjZSBlbmNoYW50bWVudCBnbGludCBjb2xvciB3aXRoIG1vcmUgbWF0Y2hpbmcgY29sb3JzIGZvciBzb21lIHZhbmlsbGEgaXRlbXM/IFtkZWZhdWx0OiB0cnVlXQ0KICAgIEI6IkN1c3RvbSBFbmNoYW50bWVudCBDb2xvcnMgZm9yIFZhbmlsbGEgSXRlbXMiPXRydWUNCg0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIHBvcnRmb3J3YXJkIHlvdXIgbG9jYWwgd29ybGQgd2hlbiB5b3Ugc2hhcmUgd2l0aCBpdCB0byBMQU4/DQogICAgIyBUaGlzIGZlYXR1cmUgZG9lc24ndCB3b3JrIG9uIGFsbCBjbGllbnRzLCB5b3UgYXJlIGdvaW5nIHRvIGdldCBhIG1lc3NhZ2UgaW4gY2hhdCBpZiBpdCB3YXMgc3VjY2Vzc2Z1bC91bnN1Y2Nlc3NmdWwgW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiTEFOIFVQblAiPXRydWUNCg0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGFkZCBNb2QgQnJvd3NlciBmZWF0dXJlIHRvIG1haW4gbWVudT8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiTW9kIEJyb3dzZXIiPXRydWUNCg0KICAgICMgUmVwbGFjZSB2YW5pbGxhIGZ1cm5hY2UgYW5kIGJyZXdpbmcgc3RhbmQgcHJvZ3Jlc3MgYmFycyB0byB1c2Ugc21vb3RoIHJlbmRlcmluZz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiU21vb3RoIFZhbmlsbGEgR3VpcyI9dHJ1ZQ0KfQ0KDQoNCmRlYnVnIHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSBhZGQgZGVidWcgcmF5IHRyYWNlciBpdGVtPyBbZGVmYXVsdDogZmFsc2VdDQogICAgQjpSYXl0cmFjZXI9ZmFsc2UNCg0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGFkZCBkZWJ1ZyB6YXBwZXIgaXRlbT8gW2RlZmF1bHQ6IGZhbHNlXQ0KICAgIEI6WmFwcGVyPWZhbHNlDQp9DQoNCg0KaXRlbXMgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGFkZCBBY2N1bXVsYXRvciBpdGVtPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOkFjY3VtdWxhdG9yPXRydWUNCn0NCg0KDQppd3JlbmNoIHsNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpDQogICAgUzpHcmVlbj0yMkZGMjINCg0KICAgICMgV2hhdCBpcyB0aGUgY29sb3Igd2hlbiB0aGUgaG92ZXJlZCBibG9jayBpcyBOT1Qgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpDQogICAgUzpSZWQ9RkYyMjIyDQp9DQoNCg0KbmV0d29ya2luZyB7DQogICAgIyBTaG91bGQgSGFtbWVyQ29yZSB1c2Ugb2xkIG5ldHdvcmtpbmcgaW5zdGVhZCBvZiB0aGUgbmV3IChldmVudC1kcml2ZW4pIG9uZT8gW2RlZmF1bHQ6IGZhbHNlXQ0KICAgIEI6Ik9sZCBOZXR3b3JrIj1mYWxzZQ0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
Pastebin Connection: Okay.
	Suspected Mods: WrapUp (wrapup), OreDictInit (oredictinit), JAOPCA (jaopca)
	Launched Version: 1.12.2-forge1.12.2-14.23.3.2702
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 530 GL version 4.5.0 - Build 22.20.16.4749, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

**Comment by kyeiti** [comment]
> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at thelm.**jaopca**.api.EnumEntryType.lambda$getRegisterer$12(EnumEntryType.java:115)

Going by the error here, it's jaopca which is crashing.
It even says so itself:

> Suspected Mods: WrapUp (wrapup), OreDictInit (oredictinit), JAOPCA (jaopca)

**Comment by Los2tale** [comment]
but it work fine before i install this. Does this mean JAOPCA not compatible with this mod ,right?

**Comment by kyeiti** [comment]
I suspect there is at least one more mod involved, since it works fine with just UB and JAOPCA.

If you can find the smallest amount of mods to cause the crash I will take a closer look - I'm not going to dig through 106 mods though.

An other point of interest: Did you just add UB to your pack or did you update it from a 1.0.*-version (and it worked before)?

**Comment by Los2tale** [comment]
i find that error happen cuz aether_ii

**Comment by kyeiti** [comment]
I could not reproduce the crash with the latest Aether II. Maybe they changed something on their end, since  it just updated?

**Comment by kyeiti** [comment]
Closed due to inactivity.
