### ISSUE TITLE
A Small Crash In My Modpack While Creating The World

### ISSUE THREAD

**Issue by kenijey** [kyeiti/UndergroundBiomesConstructs#13]
[crash-2018-05-24_00.31.47-server.txt](https://github.com/kyeiti/UndergroundBiomesConstructs/files/2032941/crash-2018-05-24_00.31.47-server.txt)

1.12.2...
forge 2702...

**Comment by kenijey** [comment]
it happened only once..

**Comment by kenijey** [comment]
oops, it happened again.
[crash-2018-05-24_01.07.42-server.txt](https://github.com/kyeiti/UndergroundBiomesConstructs/files/2033040/crash-2018-05-24_01.07.42-server.txt)
same crash, happens sometimes.. hope you fix it

**Comment by kenijey** [comment]
and think the actual problem is, ATG tries to place some andesite/diorite/granite blocks, but i disabled vanilla andesite/diorita/granite in UBC configs: **_B:DisableVanillaStoneVariants=true_**
i think it causes this crash.

**Comment by kyeiti** [comment]
Hm, going by the crash report it looks more like a problem with sand and replacing cobblestones with ubified cobblestones.

**Comment by kenijey** [comment]
as i said, it happens when i enable this config:
B:DisableVanillaStoneVariants=true

**Comment by kyeiti** [comment]
I honestly cannot see a relation between the crash that option. The crash report is very clear on what nees to be done to prevent it though, so I should have it fixed with the next patch.

**Comment by kenijey** [comment]
okay np. just letting u know :p thanks for fix and updating the great mod.
