### ISSUE TITLE
[1.1.3] Wrong tool type and mining level  for some mod ore.

### ISSUE THREAD

**Issue by Sinxar** [kyeiti/UndergroundBiomesConstructs#16]
Hello!

I discovered a few oddities with some mod ores that I am using. 

Thermal Foundation Destabilized Redstone requires a pickaxe to mine in normal stone, but needs a shovel in UBC stone.

Biomes o Plenty gems require mining level diamond in regular stone but they are obsidian level in UBC stone.

You can reproduce by installing these mods:
Forge 2705
![untitled](https://user-images.githubusercontent.com/3210315/40627173-6f4cb7aa-628b-11e8-82a4-e57da531827a.png)
Also biomes o plenty for testing the gemstone ore.

Then place 1 of each type of destabilized redstone and 1 of each biome o plenty ore. 

You may want The One Probe to view the harvestability if testing like this.

Here are some more screenshots of the issue in my minimal mod test world.

Destabilized Redstone:
![2018-05-28_15 08 59](https://user-images.githubusercontent.com/3210315/40627300-31ba3272-628c-11e8-9344-bb6f74dee652.png)
![2018-05-28_15 09 03](https://user-images.githubusercontent.com/3210315/40627299-31b2026e-628c-11e8-84a4-fd6b93aba6ba.png)

Gemstone Ore example:
![2018-05-28_15 21 39](https://user-images.githubusercontent.com/3210315/40627255-fdfd2354-628b-11e8-85dc-695cac1ca269.png)
![2018-05-28_15 21 42](https://user-images.githubusercontent.com/3210315/40627256-fe10312e-628b-11e8-8017-7462e368630d.png)

**Comment by kyeiti** [comment]
Thank you for this amazing bug report. This will be fixed in the next patch.
