### ISSUE TITLE
Custom ores flickering

### ISSUE THREAD

**Issue by whitestarx0312** [kyeiti/UndergroundBiomesConstructs#18]
Forge: forge-14.23.3.2697
UBC: UndergroundBiomesConstructs-1.12-1.1.3
Optifine: preview_OptiFine_1.12.2_HD_U_D2_pre

Issue: All custom ores have flickering textures, likely due to an optifine interaction. 
Images: https://imgur.com/a/LXxBFVq

**Comment by kyeiti** [comment]
Cannot reproduce this with OptiFine_1.12.2_HD_U_D2 (I can't find the pre-Version). I suspect it's related to those .01-numbers in the model though, so I'll remove them for the next patch.
