### ISSUE TITLE
[1.12.2] [Request] Add Support for Abyssalcraft

### ISSUE THREAD

**Issue by Sanofus** [kyeiti/UndergroundBiomesConstructs#21]
Support for Coralium, Dreadium and Nitre ore in the overworld.

**Comment by kyeiti** [comment]
I could not find a Dreadium Ore in Abyssalcraft. (I did find an Abyssalnite Ore though.)

In any case I could not figure out how Abyssalcraft "encrypts" the names of some items (like the Abyssalnite Ore), so you'll have to do without it... (and I'll not really support it.) Also Coralium Ore doesn't really look nice, when removing the background (the overlay would need semi-transparent pixels to make it look nice, but that does not work (yet?))

Anyway, here is an abyssalnite.json for UB 1.2.0:
```JSON
[
  {
    "internalOreName": "abyssalcraft:nitreore",
    "meta": -1,
    "overlay": "undergroundbiomes:blocks/overlays/custom/ore_contrast2",
    "color": "#71653a",
    "oreDirectories": []
  },
  {
    "internalOreName": "abyssalcraft:abyore",
    "meta": -1,
    "overlay": "undergroundbiomes:blocks/overlays/custom/ore_contrast2",
    "color": "#5b22a9",
    "oreDirectories": []
  },
  {
    "internalOreName": "abyssalcraft:coraliumore",
    "meta": -1,
    "overlay": "undergroundbiomes:blocks/overlays/custom/gem",
    "color": "#358b95",
    "oreDirectories": []
  }
]
```

**Comment by Sanofus** [comment]
Indeed I meat abyssalnite ore. Sorry for that.

**Comment by Sanofus** [comment]
Tested and works fine. Thank you.
