### ISSUE TITLE
[Compatability Issue] Quarries from Ancient Warfare 2 dig stone as smooth instead of cobblestone.

### ISSUE THREAD

**Issue by Thessil** [kyeiti/UndergroundBiomesConstructs#22]
As the title says, the quarry will dig up certain stone types that are supposed to be cobblestone without silk touch as smooth stone type. They mentioned it had to do with how this mod defines drops from Underground Biomes stone differently than vanilla stone.

**Comment by kyeiti** [comment]
I must have overlooked this while updating to 1.12. Thanks for letting me know!
