### ISSUE TITLE
[Request] Way to make UBC stone into vanilla

### ISSUE THREAD

**Issue by charlesbevans** [kyeiti/UndergroundBiomesConstructs#24]
Some mods don't handle the UBC stone. Roots 2, for example, doesn't recognize UBC stone when making runestones. I'd like a way to make it vanilla. Maybe make a 2x2 of different stone types to make vanilla stone?

**Comment by Sanofus** [comment]
You can craft vanilla cobblestone with 2x2 UB cobblestone. 2x2 UB stone will result in UB stone bricks.

**Comment by Sanofus** [comment]
Second advice is to add Craftweaker. Craftweaker is able to add recipes that are ordicted if have issue with mods that have recipes with ressources missing oredictionary.

**Comment by charlesbevans** [comment]
Ok, that wasn't in JEI. As for CraftTweaker, I thought something so basic was better included in the mod.
