### ISSUE TITLE
[Request] Stone Variant Support For Quark Speleothems

### ISSUE THREAD

**Issue by Darkiceflame** [kyeiti/UndergroundBiomesConstructs#44]
The Quark mod added new stalactite-like blocks in a recent update, but they tend to clash with this mod's stone variants. Would it be possible to add support for speleothems?

**Comment by Aang23** [comment]
That has already been request and will be added in UBC 1.3.2.
https://github.com/Aang23/UndergroundBiomesConstructs/issues/30
