### ISSUE TITLE
Support for modded ores

### ISSUE THREAD

**Issue by DaKingCartoon** [kyeiti/UndergroundBiomesConstructs#5]
support for modded ores, or an api for such just like in the original UBC, to better make the world more uniform

**Comment by kyeiti** [comment]
I'm working on it.

Here is the progess:
- [x] Read ores to change from json-files to allow configuration and extension by the user (/pack maker).
- [ ] Add textures and default settings
  - [x] Actually Additions
  - [ ] Applied Energestics
  - [ ] Base Metals
  - [ ] Base Minerals
  - [ ] Better Underground
  - [x] Biomes O'Plenty (Ugly texture though)
  - [ ] Draconic Evolution
  - [ ] Ender Ore
  - [ ] Extreme Reactors
  - [x] Forestry
  - [x] Immersive Engineering
  - [x] Industrial Craft
  - [ ] Mekanism
  - [ ] Modern Metals
  - [ ] RFTools Dimensions
  - [ ] Tech Reborn
  - [ ] Thaumcraft
  - [x] Thermal Foundation

> or an api for such just like in the original UBC

I don't remember removing it. This is an update to the original UBC, not a recreation.
