### ISSUE TITLE
[1.12.2] [Forge 2701] Infinity Stairs

### ISSUE THREAD

**Issue by Sanofus** [kyeiti/UndergroundBiomesConstructs#7]
I crafted black granite stairs. If you set them to the world the number in your inventory do not decrease. You have though unlimited stairs. 
![2018-05-21_01 04 54](https://user-images.githubusercontent.com/26455012/40284725-bdd3bed0-5c93-11e8-8475-0a581534e6c6.png)
![2018-05-21_01 04 58](https://user-images.githubusercontent.com/26455012/40284726-bf90aeb8-5c93-11e8-8e47-9e7c4948c6c6.png)

**Comment by kyeiti** [comment]
Thanks for pointing this out! (I suppose I should start building a proper house to notice such things...)
