### ISSUE TITLE
[1.12.] severe problem on start up

### ISSUE THREAD

**Issue by Sanofus** [kyeiti/UndergroundBiomesConstructs#8]
[crash-2018-05-21_16.31.21-client.txt](https://github.com/kyeiti/UndergroundBiomesConstructs/files/2022938/crash-2018-05-21_16.31.21-client.txt)
[crash-2018-05-21_16.34.04-client.txt](https://github.com/kyeiti/UndergroundBiomesConstructs/files/2022939/crash-2018-05-21_16.34.04-client.txt)

**Comment by kyeiti** [comment]
Apparently the build process failed me -.-

Sorry, I'm uploading a new build now
